CREATE TABLE dog (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created TIMESTAMP DEFAULT now(),
    image_url TEXT,
    image_desc TEXT,
    name TEXT,
    sex TEXT,
    age INT, 
    breed TEXT,
    story TEXT
)

CREATE TABLE cat (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created TIMESTAMP DEFAULT now(),
    image_url TEXT,
    image_desc TEXT,
    name TEXT,
    sex TEXT,
    age INT, 
    breed TEXT,
    story TEXT
)